name: SCA Python

on:
  push:
    branches:
      - "master"

jobs:
  perform-sca-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout python app
        uses: actions/checkout@v3
        with:
          repository: swinton/github-app-demo.py

      - name: Contrast SCA Action
        uses: Contrast-Security-OSS/contrast-sca-action@main
        with:
          apiKey: ${{ secrets.CONTRAST_API_KEY }}
          orgId: ${{ secrets.CONTRAST_ORGANIZATION_ID }}
          authHeader: ${{ secrets.CONTRAST_AUTH_HEADER }}
          apiUrl: ${{ secrets.CONTRAST_API_URL }}
          fail: true
          severity: high
          filePath: .
